blue_bear_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derri√®re les noisettes
        description: Des noisettes et des livres
        bootstrap: true
    admins:
        user:
            entity: BlueBear\CmsUserBundle\Entity\User
            form: user